# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWidow(object):
    def setupUi(self, LoginWidow):
        LoginWidow.setObjectName("LoginWidow")
        LoginWidow.resize(515, 444)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWidow.sizePolicy().hasHeightForWidth())
        LoginWidow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(LoginWidow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 13, 484, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    font:50px;\n"
"    color:rgb(255, 255, 255)\n"
"\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.AutoLoginCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.AutoLoginCheckBox.setMinimumSize(QtCore.QSize(200, 0))
        self.AutoLoginCheckBox.setObjectName("AutoLoginCheckBox")
        self.gridLayout.addWidget(self.AutoLoginCheckBox, 2, 2, 1, 1)
        self.PassEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.PassEdit.setMinimumSize(QtCore.QSize(200, 50))
        self.PassEdit.setStyleSheet("QLineEdit\n"
"{\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 3px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: #F2F2F2; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"\n"
"\n"
"}\n"
"QLineEdit:hover{ /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: #F2F2F2;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"")
        self.PassEdit.setInputMask("")
        self.PassEdit.setText("")
        self.PassEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassEdit.setObjectName("PassEdit")
        self.gridLayout.addWidget(self.PassEdit, 1, 1, 1, 2, QtCore.Qt.AlignLeft)
        self.RemebercheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemebercheckBox.sizePolicy().hasHeightForWidth())
        self.RemebercheckBox.setSizePolicy(sizePolicy)
        self.RemebercheckBox.setObjectName("RemebercheckBox")
        self.gridLayout.addWidget(self.RemebercheckBox, 2, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.IdEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.IdEdit.setMinimumSize(QtCore.QSize(200, 50))
        self.IdEdit.setStyleSheet("QLineEdit\n"
"{\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 3px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: #F2F2F2; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"\n"
"\n"
"}\n"
"QLineEdit:hover{ /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: #F2F2F2;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"")
        self.IdEdit.setInputMask("")
        self.IdEdit.setText("")
        self.IdEdit.setObjectName("IdEdit")
        self.gridLayout.addWidget(self.IdEdit, 0, 1, 1, 2, QtCore.Qt.AlignLeft)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout)
        self.LoginButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoginButton.sizePolicy().hasHeightForWidth())
        self.LoginButton.setSizePolicy(sizePolicy)
        self.LoginButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.LoginButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LoginButton.setAutoFillBackground(False)
        self.LoginButton.setStyleSheet("/* Red Button */\n"
"QPushButton{\n"
"    border-radius: 8px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-size: 30px;\n"
"    height:50px;\n"
"    width:150px;\n"
"    border: 2px solid #f44336;\n"
"    \n"
"    \n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    color: black;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: red;\n"
"}\n"
"\n"
"\n"
"")
        self.LoginButton.setAutoDefault(False)
        self.LoginButton.setDefault(False)
        self.LoginButton.setFlat(False)
        self.LoginButton.setObjectName("LoginButton")
        self.verticalLayout.addWidget(self.LoginButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RegisterButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RegisterButton.sizePolicy().hasHeightForWidth())
        self.RegisterButton.setSizePolicy(sizePolicy)
        self.RegisterButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.RegisterButton.setStyleSheet("/* Red Button */\n"
"QPushButton{\n"
"    border-radius: 8px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-size: 20px;\n"
"    height:50px;\n"
"    width:100px;\n"
"    border: 2px solid #f44336;\n"
"    \n"
"    \n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    color: black;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: red;\n"
"}\n"
"\n"
"")
        self.RegisterButton.setObjectName("RegisterButton")
        self.horizontalLayout.addWidget(self.RegisterButton)
        self.AboutButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AboutButton.sizePolicy().hasHeightForWidth())
        self.AboutButton.setSizePolicy(sizePolicy)
        self.AboutButton.setStyleSheet("/* Red Button */\n"
"QPushButton{\n"
"    border-radius: 8px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-size: 20px;\n"
"    height:50px;\n"
"    width:100px;\n"
"    border: 2px solid #f44336;\n"
"    \n"
"    \n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    color: black;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: red;\n"
"}\n"
"\n"
"")
        self.AboutButton.setObjectName("AboutButton")
        self.horizontalLayout.addWidget(self.AboutButton)
        self.QuitButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuitButton.sizePolicy().hasHeightForWidth())
        self.QuitButton.setSizePolicy(sizePolicy)
        self.QuitButton.setStyleSheet("/* Red Button */\n"
"QPushButton{\n"
"    border-radius: 8px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-size: 20px;\n"
"    height:50px;\n"
"    width:100px;\n"
"    border: 2px solid #f44336;\n"
"    \n"
"    \n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    color: black;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: red;\n"
"}\n"
"\n"
"")
        self.QuitButton.setObjectName("QuitButton")
        self.horizontalLayout.addWidget(self.QuitButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        LoginWidow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWidow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 22))
        self.menubar.setObjectName("menubar")
        LoginWidow.setMenuBar(self.menubar)

        self.retranslateUi(LoginWidow)
        self.QuitButton.clicked.connect(LoginWidow.close)
        QtCore.QMetaObject.connectSlotsByName(LoginWidow)

    def retranslateUi(self, LoginWidow):
        _translate = QtCore.QCoreApplication.translate
        LoginWidow.setWindowTitle(_translate("LoginWidow", "MainWindow"))
        self.label.setText(_translate("LoginWidow", "微博热点提取软件"))
        self.AutoLoginCheckBox.setText(_translate("LoginWidow", "自动登陆"))
        self.RemebercheckBox.setText(_translate("LoginWidow", "记住密码"))
        self.label_2.setText(_translate("LoginWidow", "账号："))
        self.label_3.setText(_translate("LoginWidow", "密码："))
        self.LoginButton.setText(_translate("LoginWidow", "登录"))
        self.RegisterButton.setText(_translate("LoginWidow", "注册"))
        self.AboutButton.setText(_translate("LoginWidow", "关于"))
        self.QuitButton.setText(_translate("LoginWidow", "退出"))
