# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'information_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformationDialog(object):
    def setupUi(self, InformationDialog):
        InformationDialog.setObjectName("InformationDialog")
        InformationDialog.resize(512, 510)
        self.layoutWidget = QtWidgets.QWidget(InformationDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 101, 371, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("font-size:25px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.IdLabel = QtWidgets.QLabel(self.layoutWidget)
        self.IdLabel.setStyleSheet("font-size:20px")
        self.IdLabel.setText("")
        self.IdLabel.setObjectName("IdLabel")
        self.gridLayout.addWidget(self.IdLabel, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("font-size:25px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.nicklabel = QtWidgets.QLabel(self.layoutWidget)
        self.nicklabel.setStyleSheet("font-size:25px;")
        self.nicklabel.setText("")
        self.nicklabel.setObjectName("nicklabel")
        self.gridLayout.addWidget(self.nicklabel, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("font-size:25px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.sexlabel = QtWidgets.QLabel(self.layoutWidget)
        self.sexlabel.setStyleSheet("font-size:25px;")
        self.sexlabel.setText("")
        self.sexlabel.setObjectName("sexlabel")
        self.gridLayout.addWidget(self.sexlabel, 2, 1, 1, 1)
        self.alterButton = QtWidgets.QPushButton(self.layoutWidget)
        self.alterButton.setStyleSheet("QPushButton\n"
"{\n"
"background-color:rgba(255, 255, 255, 0);\n"
"border-radius: 8px;\n"
"width:150px;\n"
"height:50px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"font-size: 16px;\n"
"\n"
"color:rgb(255, 255, 255);\n"
"border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(199, 255, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:40px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:20px;\n"
"}")
        self.alterButton.setObjectName("alterButton")
        self.gridLayout.addWidget(self.alterButton, 3, 0, 1, 1)
        self.ConcelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ConcelButton.setStyleSheet("QPushButton\n"
"{\n"
"background-color:rgba(255, 255, 255, 0);\n"
"border-radius: 8px;\n"
"width:150px;\n"
"height:50px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"font-size: 16px;\n"
"\n"
"color:rgb(255, 255, 255);\n"
"border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(199, 255, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:40px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:20px;\n"
"}")
        self.ConcelButton.setObjectName("ConcelButton")
        self.gridLayout.addWidget(self.ConcelButton, 3, 1, 1, 1)

        self.retranslateUi(InformationDialog)
        QtCore.QMetaObject.connectSlotsByName(InformationDialog)

    def retranslateUi(self, InformationDialog):
        _translate = QtCore.QCoreApplication.translate
        InformationDialog.setWindowTitle(_translate("InformationDialog", "Dialog"))
        self.label.setText(_translate("InformationDialog", "用户id："))
        self.label_2.setText(_translate("InformationDialog", "昵称："))
        self.label_3.setText(_translate("InformationDialog", "性别："))
        self.alterButton.setText(_translate("InformationDialog", "修改密码"))
        self.ConcelButton.setText(_translate("InformationDialog", "取消"))
