# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scrapy_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScrapyDialog(object):
    def setupUi(self, ScrapyDialog):
        ScrapyDialog.setObjectName("ScrapyDialog")
        ScrapyDialog.resize(1124, 566)
        self.widget = QtWidgets.QWidget(ScrapyDialog)
        self.widget.setGeometry(QtCore.QRect(950, 210, 162, 116))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setStyleSheet("QComboBox{border:1px solid rgb(204,204,204);border-radius:3px;height:28px;}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.backButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setMinimumSize(QtCore.QSize(0, 50))
        self.backButton.setStyleSheet("QPushButton\n"
"{\n"
"background-color:rgba(255, 255, 255, 0);\n"
"border-radius: 8px;\n"
"width:150px;\n"
"height:50px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"font-size: 16px;\n"
"\n"
"color:rgb(255, 255, 255);\n"
"border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(199, 255, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:40px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:20px;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.verticalLayout.addWidget(self.backButton)

        self.retranslateUi(ScrapyDialog)
        QtCore.QMetaObject.connectSlotsByName(ScrapyDialog)

    def retranslateUi(self, ScrapyDialog):
        _translate = QtCore.QCoreApplication.translate
        ScrapyDialog.setWindowTitle(_translate("ScrapyDialog", "Dialog"))
        self.label.setText(_translate("ScrapyDialog", "一致性：0"))
        self.comboBox.setItemText(0, _translate("ScrapyDialog", "人物关系图"))
        self.comboBox.setItemText(1, _translate("ScrapyDialog", "数量柱状图"))
        self.comboBox.setItemText(2, _translate("ScrapyDialog", "数量比例图"))
        self.comboBox.setItemText(3, _translate("ScrapyDialog", "LDA-jieba图"))
        self.comboBox.setItemText(4, _translate("ScrapyDialog", "LDA-thulac图"))
        self.comboBox.setItemText(5, _translate("ScrapyDialog", "LDA-pkuseg图"))
        self.comboBox.setItemText(6, _translate("ScrapyDialog", "LDA-snowlp图"))
        self.backButton.setText(_translate("ScrapyDialog", "返回"))
